### ISSUE TITLE
Apple Silicon stops rendering after first frame (seemingly)

### ISSUE THREAD

**Issue by L422Y** [ktnrg45/pyremoteplay#8]
Everything almost works and then it spits this out, and video stream stops rendering after one (or a few?) frames, I can control it for a while and then an error pops up: "Decoder could not keep up. Try lowering the framerate / resolution"

I imagine it is because of an incompatibility with arm64 / Apple Silicon, but strange how the first frame works.. is it sent as a static image?

`WARNING:libav.swscaler:No accelerated colorspace conversion found from yuv420p to rgb24.
WARNING:pyremoteplay.av:AV Handler max queue size exceeded`

**Comment by ktnrg45** [comment]
This is probably an issue with pyav/FFMPEG. You may need a custom build of FFMPEG. One thing that you could try is to enable the 'Use OpenGL' option. This should let OpenGL handle the yuv420p to rgb conversion instead of pyav.

**Comment by ktnrg45** [comment]
The video stream is a raw h264 or hevc bitstream.

Looking at [libswscale](https://github.com/libav/libav/tree/master/libswscale), it seems that there is no optimized conversion written for ARM64. So the conversion will be using the generic unoptimized code which is slower. The error about the decoder not keeping up also points to this. Bottom line is that the stream cannot be decoded fast enough.

Will be closing this soon since this seems to be a pyav/FFMPEG issue, but would be interested to hear if enabling OpenGl will resolve this.

**Comment by L422Y** [comment]
Check out [this thread](https://trac.ffmpeg.org/timeline?from=2022-06-02T08%3A07%3A39%2B03%3A00&precision=second) on ffmpeg's trac, where a patch for h264 decoding on m1 has been posted (3 weeks ago)
